# Use Python 3.8 Slim as the base image to keep the image size down
FROM python:3.8-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container and install Python dependencies
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of your application's code into the container
COPY . /app/

# Command to run your application
CMD ["python", "etl_process/airport_data/airport_etl.py"]
